Add more types and corrosponding spec tests
voxpupuli/puppet-tea pull request #14
Opened 2016-10-10 13:52 UTC by b4ldr

Hi I have added some more custom types and created some tests as well as adding some boiler plat stuff from retrospect puppet.  you probably dont want to accept all if this but if there is anything you like i could create a pull request with just thoughs elements

2016-10-10 18:17 UTC, bastelfreak commented
Hi @b4ldr, thanks for the great work! Can you please take a look at the merge conflicts?

2016-10-10 18:32 UTC, bastelfreak requested changes

2016-10-10 18:32 UTC, bastelfreak commented on .fixtures.yml
> +        ref: 4.12.0
can you drop the ref please? We try to always test against master, to early detect bugs.

2016-10-10 18:32 UTC, bastelfreak commented on .puppet-lint.rc
> +# Use this file to instruct puppet-lint to ignore certain checks.
can you please remove the file? We manage all the puppet-lint settings in our `Rakefile`.

2016-10-10 18:32 UTC, bastelfreak commented on .travis.yml
>  ---
all these changes will be overwritten by our modulesync_config:
https://github.com/voxpupuli/modulesync_config/blob/master/config_defaults.yml#L2-L23

Which results in this travis file:
https://github.com/voxpupuli/puppet-tea/blob/master/.travis.yml

Our current template allows a few customizations, let me know if any of the underlying changes are still needed.

2016-10-10 18:32 UTC, bastelfreak commented on DEVELOPMENT.md
> +# module name
We have a similar file in .github/CONTRIBUTING.md. Is this file still relevant? Maybe we should merge it?

2016-10-10 18:32 UTC, bastelfreak commented on Gemfile
>  source "https://rubygems.org"
The whole file is managed by our modulesync_config:
https://github.com/voxpupuli/modulesync_config/blob/master/config_defaults.yml#L24-L61

which results in:
https://github.com/voxpupuli/puppet-tea/blob/master/Gemfile

are any of the changes here still needed?

2016-10-10 18:32 UTC, bastelfreak commented on README.markdown
can you rename it into README.md?

2016-10-10 18:32 UTC, bastelfreak commented on Rakefile
>  require 'puppetlabs_spec_helper/rake_tasks'
same here, completely managed by modulesync:
https://github.com/voxpupuli/modulesync_config/blob/master/config_defaults.yml#L62-L71

let me know if any of the changes are needed and we will fiddle something out.

2016-10-10 18:32 UTC, bastelfreak commented on examples/init.pp
> -class tea {
any reason for removing this and the other example?

2016-10-10 18:32 UTC, bastelfreak commented on metadata.json
> +  "version": "0.2.4",
please don't adjust the version number. we will take care of it during the release process.

2016-10-10 18:32 UTC, bastelfreak commented on spec/spec_helper.rb
> +require 'puppetlabs_spec_helper/module_spec_helper'
this file is also managed by modulesync. Any of the changes still needed? Prefered way for customazation is to throw the code into a spec/spec_helper_methods.rb and include it here. Example:
https://github.com/voxpupuli/puppet-zabbix/blob/master/spec/spec_helper.rb#L15
https://github.com/voxpupuli/puppet-zabbix/blob/master/.sync.yml#L4-L5
https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/spec/spec_helper.rb#L15-L17

2016-10-10 18:33 UTC, bastelfreak commented
also if you could split this up into seperate commits that would be great, it can stay in one PR.

2016-10-11 11:14 UTC, b4ldr commented
i have redone this in https://github.com/voxpupuli/puppet-tea/pull/15

2016-10-11 11:14 UTC, closed without merging