Vocpupuli pull withcommits
voxpupuli/puppet-tea pull request #16
Opened 2016-10-11 11:13 UTC by b4ldr

@bastelfreak i think most of your comments where to do with me using retrospec puppet to create a bunch of boilerplate stuff.  I have no removed that and just added the changes i have made to the types, spec, readme and fixtures files.

Currently this is not building do to 
```
ruby_dep-1.5.0 requires ruby version >= 2.2.5, which is incompatible with the
```

i fixed this in my Gemfile by adding
```ruby
gem "listen", "<=3.0.6"
```

however after looking at your example the following may be better

```ruby
gem "listen", "<=3.0.6" if :require => false RUBY_VERSION < '2.2.5'
```

however im not an expert in ruby and im not familiar with plugin sync so i thought i would leave this for now.  let me know if there is anything else you want to see.  i have closed the other pull request however i have left the branch on my repo incase something was missed

2016-10-11 14:50 UTC, domcleal requested changes

2016-10-11 14:50 UTC, domcleal commented on README.md
> +#### Table of Contents
This file's already here as README.markdown, can you remove the old one? (Git/GitHub should automatically see the rename.)

2016-10-11 14:50 UTC, domcleal commented on .fixtures.yml
> +      stdlib:
Is this required? I can't see where.

2016-10-11 14:50 UTC, domcleal commented on spec/aliases/puppetcontent_spec.rb
> +          "/Users//nope"
missing commas here, causing a syntax error in tests

2016-10-11 14:50 UTC, domcleal commented
Some of the new types are now in stdlib's master branch, are you sure they should be here too? (https://github.com/puppetlabs/puppetlabs-stdlib/commit/83539371e5b1e6ff412eda48c3a725653c506ece)

2016-10-11 16:12 UTC, b4ldr commented on .fixtures.yml
> +      stdlib:
to you mean stdlib? its possible it is not needed i think i just added without thinking

2016-10-11 16:17 UTC, b4ldr commented
Yes i noticed some of them in stdlib.  The reason i have added them here is 
  1) there has not been a release of stdlib which includes those types so i can not use them in production environments
  2)  The old validate functions have been deprecated so even when stdlib releases a new version it will be far to noisey to use in my current environment as there are many many modules which will start throwing warnings.  

I will maintain my own branch regardless so happy to remove the duplicates if thats the prfrerence

2016-10-12 07:13 UTC, roidelapluie commented
@domcleal @b4ldr if stdlib gets types now, then this module is useless. We should just merge our types to stdlib

2016-10-12 10:19 UTC, bastelfreak commented
@roidelapluie I am not sure about that approach. stdlib always needs ages for new releases. I would be happy if we could keep the types here that aren't in stdlib.

2016-10-12 11:39 UTC, roidelapluie commented
@bastelfreak «stdlib always needs ages for new releases» that is NOT a good point.

In this regard, I think keeping puppet-tea is BAD. Instead of VoxPupuli putting everything in its namespace, VP members should learn to contribute to existing repositories instead of creating their own.

2016-10-13 07:16 UTC, domcleal commented on .fixtures.yml
> +      stdlib:
Yes, stdlib - it can probably be removed, there's no dependency on it that I can see.

2017-01-01 06:23 UTC, juniorsysadmin commented
@roidelapluie @b4ldr @bastelfreak @domcleal Given a number of types from puppet-tea are now in stdlib 4.13.1 is this Pull Request still needed?

2017-01-12 11:49 UTC, b4ldr commented
Im happy for this to get closed.  I havn't had a chance to move to the latest stdlib myself but once i do ill create a pull request there

2017-01-12 11:49 UTC, closed without merging